export const arr = [
  "General Information",
  "Patient Signature",
  "What will happen during this study",
  "How are you doing today",
  "What will happen after this study",
  "The things you are committing to",
  "What happens if you cancel this study",
  "Potential compensation for this study",
  // 9,
  // 10,
  // 11,
  // 12,
  // 13,
  // 14,
  // 15,
  // 16,
  // 17,
  // 18,
  // 19,
  // 20,
]
